export const REDUX_CONSTANTS = {
    FETCH_TODOS: "FETCH_TODOS",
    UPDATE_ALERT_MESSAGE: 'UPDATE_ALERT_MESSAGE',
    CLEAR_ALERT_MESSAGE: 'CLEAR_ALERT_MESSAGE',
    START_LOADER: 'START_LOADER',
    STOP_LOADER: 'STOP_LOADER',
    DYNAMIC_CONTENT_CON_HEIGHT: 'DYNAMIC_CONTENT_CON_HEIGHT',
    FETCH_STATUS_LIST: "FETCH_STATUS_LIST",
    FETCH_CATEGORY_LIST: "FETCH_CATEGORY_LIST",
    FETCH_SEVERITY_LIST: "FETCH_SEVERITY_LIST",
    FETCH_SORT_OPTIONS: "FETCH_SORT_OPTIONS"
};